config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resource :post_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:show, :index, :edit, :update] do
    resource :follows, only: [:create, :destroy]
    get 'followings' => 'follows#followings', as: 'followings'
    get 'followers' => 'folllows#followers', as: 'followers'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy


  has_many :follows, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy
  has_many :revers_of_follows, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :follows, source: :followed
  has_many :followers, through: :revers_of_follows, source: :follower

  has_one_attached :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def follow(user_id)
    follows.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follows.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]
  
  def after_sign_in_path_for(resource)
    user_path(resource)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
  
  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @user = User.find(current_user.id)
    @book = Book.new
    @books = Book.all
  end

  def create
    @user = User.find(current_user.id)
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @book_new = Book.new
    @post_comment = PostComment.new
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
    @user = User.find(current_user.id)
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.delete
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    unless @book.favorited_by?(current_user)
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    redirect_to books_path
    end
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    redirect_to books_path
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def create
    current_user.follow(params[:use_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @post_comment = PostComment.new(post_comment_params)
    @post_comment.user_id = current_user.id
    @post_comment.book_id = @book.id
    @post_comment.save
    redirect_to book_path(@book.id)
  end

  def destroy
    @book = Book.find(params[:book_id])
    @post_comment = current_user.post_comments.find_by(book_id: @book.id)
    @post_comment.destroy
    redirect_to book_path(@book.id)
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.find(current_user.id)
    @book = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follow_helper.rb
module FollowHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_comment.html.erb
<table>
  <% @book.post_comments.each do |post_comment| %>
    <% post_comment_user = post_comment.user %>
    <tr>
    	<td>
  		<%= link_to user_path(post_comment_user), class: "user_#{post_comment_user.id}" do %>
    		<%= image_tag post_comment.user.get_profile_image(100,100) %><br>
    		<%= post_comment_user.name %>
  		<% end %>
    	</td>
    	<td><%= post_comment.comment %></td>
    	<% if current_user == post_comment_user %>
      <td><%= link_to 'Destroy', book_post_comments_path(post_comment.book_id, post_comment.id), class: 'btn-sm btn-danger', method: :delete %></td>
    	<% end %>
    </tr>
  <% end %>
</table>
<%= form_with model: [@book,@post_comment], local: true do |f| %>
  <%= f.text_area :comment, size:"90x5" %><br>
  <%= f.submit '送信'%>
<% end %>

app/views/books/_favorites.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete do %>
    <i class="fas fa-heart"></i><%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post do %>
    <i class="far fa-heart"></i><%= book.favorites.count %>
  <% end %>
<% end %>

app/views/books/_userinfo.html.erb
<h2>User info</h2>
<%= image_tag current_user.get_profile_image(100, 100) %>
<table class="table">
  <tr>
    <th>name</th>
    <th><%= current_user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= current_user.introduction %></th>
  </tr>
</table>
<%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-block" do %>
  <i class="fas fa-user-cog"></i>
<% end %>

<h2 class="mt-3">New book</h2>

<%= form_with model: Book.new do |f| %>
<div class="form-group">
  <label for="book-title">Title</label>
  <p><%= f.text_field :title, class: "form-control" %></p>
</div>
<div class="form-group">
  <label for="book-opinion">Opinion</label>
  <p><%= f.text_area :body, class: "form-control" %></p>
</div>
<div class="form-group">
  <%= f.submit 'Create Book', {class: "btn btn-success"} %>
</div>
<% end %>

app/views/books/edit.html.erb
<p></p>
<div class="container"> 
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
        <% if @book.errors.any? %>
          <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      <%= form_with model: @book, local:true do |f| %>
      <div class="form-group">
        <label for="book-title">Title</label>
        <%= f.text_field :title, value: @book.title, class: "form-control title" %>
      </div>
      <div class="form-group">
        <label for="book-opinion">Opinion</label>
        <%= f.text_area :body, value: @book.body, class: "form-control opinion" %>
      </div>
      <div class="form-group">
        <%= f.submit "Update Book", class: "btn btn-success" %>
      </div>
      <% end %>
      <%= link_to "Show", book_path %> |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p></p>
<div class="container px-5 px-sm-0">
<% if @book.errors.any? %>
  <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="row">
  <div class="col-md-3">
    <%= render 'userinfo', books: @books %>
  </div>

  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
      <table class="table table-hover">
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>

      <% @books.each do |book| %>
        <tr>
          <th>
            <%= link_to user_path(book.user_id) do %>
              <%= image_tag book.user.get_profile_image(100, 100) %>
            <% end %>
          </th>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
          <td id="favorites_<%= book.id %>">
            <%= render 'favorites', book: book %>
          </td>
          <td>コメント件数：<%= book.post_comments.count %></td>
          </th>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p>
  <%= flash[:notice] %>
</p>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @user.get_profile_image(100, 100) %>
      <table class="table">
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
      </table>
      <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: Book.new do |f| %>
      <div class="form-group">
        <label for="book-title">Title</label>
        <p><%= f.text_field :title, class: "form-control" %></p>
      </div>
      <div class="form-group">
        <label for="book-opinion">Opinion</label>
        <p><%= f.text_area :body, class: "form-control" %></p>
      </div>
      <div class="form-group">
        <%= f.submit 'Create Book', {class: "btn btn-success"} %>
      </div>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
    <table class="table">
      <tr>
        <td>
          <%= link_to user_path(@book.user_id) do %>
            <%= image_tag @book.user.get_profile_image(100, 100) %>
            <p><%= @book.user.name %></P>
          <% end %>
        </td>
        <td><%= link_to @book.title, book_path(@book.id) %></td>
        <td><%= @book.body %></td>
        <% if @book.user_id == current_user.id %>
        <td>
          <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %>
        </td>
        <td>
          <%= link_to "Destroy", book_path(@book.id), method: :delete, class: "btn btn-sm btn-danger",
          "data-confirm" => "本当に消しますか？" %>
        </td>
        <% end %>
      </tr>
    </table>
    <%= render 'books/comment', book: @book, post_comment: @post_comment %>
  </div>
</div>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/follows/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
  <table class="table table-hover">
    <tr>
      <th>image</th>
      <th>name</th>
    </tr>
    <% @users.each do |user| %>
    <tr>
      <td><%= image_tag user.get_profile_image(100, 100) %></td>
      <td><%= user.name %></td>
      <td>フォロー数：<%= user.followings.count %></td>
      <td>フォロワー数：<%= user.followers.count %></td>
      <td>
        <% if current_user != user %>
          <% if current_user.following?(user) %>
            <%= link_to "フォロー外す", user_follows_path(user.id), method: :delete %>
          <% else %>
            <%= link_to "フォローする", user_follows_path(user.id), method: :post %>
          <% end %>
        <% end %>
      </td>
      <td><%= link_to "Show", user_path(user.id) %></td>
    </tr>
    <% end %>
  </table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/follows/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <table class="table table-hover">
    <tr>
      <th>image</th>
      <th>name</th>
    </tr>
    <% @users.each do |user| %>
    <tr>
      <td><%= image_tag user.get_profile_image(100, 100) %></td>
      <td><%= user.name %></td>
      <td>フォロー数：<%= user.followings.count %></td>
      <td>フォロワー数：<%= user.followers.count %></td>
      <td>
        <% if current_user != user %>
          <% if current_user.following?(user) %>
            <%= link_to "フォロー外す", user_follows_path(user.id), method: :delete %>
          <% else %>
            <%= link_to "フォローする", user_follows_path(user.id), method: :post %>
          <% end %>
        <% end %>
      </td>
      <td><%= link_to "Show", user_path(user.id) %></td>
    </tr>
    <% end %>
  </table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">
        Welcome to
        <i class="fas fa-book"></i><strong>Bookers</strong>!
      </h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<main>
  <p>
    <%= flash[:notice] %>
  </p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>
          welcome to
          <i class="fas fa-book"></i><strong>Bookers</strong>
          !!
        </h1>
        <p>
          In
          <i class="fas fa-book"></i><strong>Bookers</strong>,
        </p>
        <p>
          you can share and exchange your opinions , inpressions , and emotions
        </p>
        <p>
          about various books!
        </p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to "Log in", user_session_path, class: 'btn btn-info btn-sm btn-block mb-3' %>
          </div>
          <div class="row">
            <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-info bg-success btn-sm btn-block' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-link User px-2">
                  <%= link_to user_path(current_user.id), class: "text-light text-decoration-none" do %>
                    <i class="fas fa-home"></i> Home
                  <% end %>
                </li-->
                <li class="nav-link User px-2">
                  <%= link_to users_path, class: "text-light text-decoration-none" do %>
                    <i class="fas fa-users"></i> Users
                  <% end %>
                </li>
                <li class="nav-link User px-2">
                  <%= link_to books_path, class: "text-light text-decoration-none" do %>
                    <i class="fas fa-book-open"></i> Books
                  <% end %>
                </li>
                <li class="nav-link User px-2">
                  <%= link_to destroy_user_session_path, method: :delete, class: "text-light text-decoration-none" do %>
                    <i class="fas fa-sign-out-alt"></i> Log out
                  <% end %>
                </li>
              <% else %>
                <li class="nav-link User px-2">
                  <%= link_to root_path, class: "text-light text-decoration-none" do %>
                    <i class="fas fa-home"></i> Home
                  <% end %>
                </li>
                <li class="nav-link User px-2">
                  <%= link_to home_about_path, class: "text-light text-decoration-none" do %>
                    <i class="fas fa-link"></i> About
                  <% end %>
                </li>
                <li class="nav-link User px-2">
                  <%= link_to new_user_registration_path, class: "text-light text-decoration-none" do %>
                    <i class="fas fa-user-plus"></i> Sign up
                  <% end %>
                </li>
                <li class="nav-link User px-2">
                  <%= link_to new_user_session_path, class: "text-light text-decoration-none" do %>
                    <i class="fas fa-sign-in-alt"></i> Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<p></p>
<div class="container"> 
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
        <% if @user.errors.any? %>
          <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      <%= form_with model: @user do |f| %>
      <div class="form-group">
        <label for="user_name">Name</label>
        <%= f.text_field :name, {class: "form-control name"} %>
      </div>
      <div class="form-group">
        <label for="user_image">Image</label>
        <p><%= f.file_field :profile_image, accept: "image/*" %></p>
      </div>
      <div class="form-group">
        <label for="user_introduction">Introduction</label>
        <%= f.text_area :introduction, {class: "form-control introduciton"} %>
      </div>
      <div class="form-group">
        <%= f.submit "Update User", class: "btn btn-secondary"%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/userinfo', user: @user, book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
    <table class="table table-hover">
      <tr>
        <th>image</th>
        <th>name</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(100, 100) %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォローを外す", user_follows_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_follows_path(user.id), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<p>
  <%= flash[:notice] %>
</p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @user.get_profile_image(100, 100) %>
      <table class="table">
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
        <tr>
          <th>follows</th>
          <td><%= link_to @user.followings.count, user_followings_path(@user) %></td>
        </tr>
        <tr>
          <th>followers</th>
          <td><%= link_to @user.followers.count, user_followers_path(@user) %></td>
        </tr>
      </table>

      <div class='row'>
        <% if current_user != @user %>
          <% if current_user.following?(@user) %>
            <%= link_to "フォロー外す", user_follows_path(@user.id), method: :delete, class: "btn btn-info" %>
          <% else %>
            <%= link_to "フォローする", user_follows_path(@user.id), method: :post, class: "btn btn-success" %>
          <% end %>
        <% else %>
          <%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        <% end %>
      </div>

      <h2 class="mt-3">New book</h2>
      <%= form_with model: Book.new do |f| %>
      <div class="form-group">
        <label for="book-title">Title</label>
        <p><%= f.text_field :title, class: "form-control" %></p>
      </div>
      <div class="form-group">
        <label for="book-opinion">Opinion</label>
        <p><%= f.text_area :body, class: "form-control" %></p>
      </div>
      <div class="form-group">
        <%= f.submit 'Create Book', {class: "btn btn-success"} %>
      </div>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover">
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
      </tr>
      <% @books.each do |book| %>
        <tr>
          <th>
            <%= link_to user_path(@user.id) do %>
              <%= image_tag book.user.get_profile_image(100, 100) %>
            <% end %>
          </th>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>